### ISSUE TITLE
mouse support in xterm?

### ISSUE THREAD

**Issue by sivann** [saitoha/xserver-SIXEL#1]
Hello, 
I successfully built this in fedora and display runs fine through xterm.
Is there a way to have mouse support so e.g. to control firefox running inside the terminal ?
Currently the mouse seems to select text.
(I run xterm through Xquartz from a remote linux host, if that is relevant, and run the xserver-sixel in there)

**Comment by sivann** [comment]
I found the solution, mouse works with mlterm but not with xterm. Thanks for the wonderful work.

**Comment by ttdoda** [comment]
Does your xterm is built with DEC locator mode support?
If not, you may rebuilt xterm with --enable-dec-locator configure option.

**Comment by sivann** [comment]
That was it, thanks. Xterm also works now.

**Comment by sivann** [comment]
Do you also have any idea how to hide xterm's own cursor (the vertical bar) because it appears along with the xsixel . mlterm does not have this issue.
